#cloud-config
# vim: syntax=yaml
#
merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

packages:
  - git
  - ansible

runcmd:
  - [ansible-pull, -U, https://github.com/cr9427/ansible.git]
