#cloud-config
# vim: syntax=yaml
#
merge_how:
 - name: list
   settings: [append]
 - name: dict
   settings: [no_replace, recurse_list]

manage_etc_hosts: true
timezone: 'Europe/Berlin'
ssh_genkeytypes: [ed25519]
ssh_pwauth: true
disable_root: true
package_update: false
package_upgrade: false

apt:
  http_proxy: 'http://apt-cache:3142/'
  https_proxy: 'false'

ssh_authorized_keys:
  - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBVtawLHGmKWf8WBPLhqksVCLvLYj+B8fev8QNEk/tVV holm@crylle.local'
  - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDShA7vPizumHqnXS9nsrJVgNRqRnTwUv8K8I13jgdL9 ubuntu@crylle.local'

users:
  - default
