#cloud-config
# vim: syntax=yaml
#
merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

packages:
  - apt-utils
  - net-tools
  - zsh
  - htop
  - vim-nox
  - psmisc
  - git
  - lsof
  - sudo
  - binutils
  - apt-utils
  - iputils-ping
  - openssh-server
  - curl
