#cloud-config
# vim: syntax=yaml
#
merge_how:
  - name: list
    settings: [append]
  - name: dict
    settings: [no_replace, recurse_list]

packages:
  - qemu-guest-agent

runcmd:
  - [systemctl, start, qemu-guest-agent]
